CREATE TABLE "transactions" (
	"id" uuid PRIMARY KEY,
	"status" varchar(50) DEFAULT 'ACTIVE',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"metadata" jsonb,
	"trans_code" varchar(64) NOT NULL UNIQUE,
	"partner_trans_id" varchar(100) NOT NULL,
	"supplier_trans_id" varchar(100),
	"provider_code" varchar(50) DEFAULT 'ANISIM' NOT NULL,
	"package_code" varchar(100) NOT NULL,
	"action" varchar(30) NOT NULL,
	"target_phone" varchar(20),
	"serial" varchar(50),
	"amount" numeric DEFAULT '0',
	"cost_amount" numeric DEFAULT '0',
	"error_code" varchar(50),
	"error_message" text,
	"lpa_string" text,
	"qr_url" varchar(500),
	"completed_at" timestamp
);
