CREATE TABLE "suppliers" (
	"id" uuid PRIMARY KEY,
	"status" varchar(20) DEFAULT 'PAUSED' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"metadata" jsonb,
	"code" varchar(50) NOT NULL UNIQUE,
	"name" varchar(255) NOT NULL,
	"adapter_type" varchar(30) NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"base_url" varchar(500) NOT NULL,
	"submit_timeout_ms" integer DEFAULT 30000 NOT NULL,
	"check_timeout_ms" integer DEFAULT 3000 NOT NULL,
	"query_timeout_ms" integer DEFAULT 10000 NOT NULL,
	"concurrency" integer DEFAULT 5 NOT NULL,
	"rate_limit_per_min" integer DEFAULT 60 NOT NULL,
	"poll_schedule_sec" jsonb DEFAULT '[5,10,20,40,60,120,300,900,1800,3600]' NOT NULL,
	"max_wait_sec" integer DEFAULT 86400 NOT NULL,
	"max_resubmit" integer DEFAULT 2 NOT NULL,
	"callback_ip_whitelist" jsonb DEFAULT '[]' NOT NULL,
	"params" jsonb DEFAULT '{}' NOT NULL,
	"secrets_enc" text
);
