CREATE TABLE "transactions" (
	"id" uuid PRIMARY KEY,
	"status" varchar(50) DEFAULT 'ACTIVE',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"metadata" jsonb,
	"transCode" varchar(20) NOT NULL,
	"partnerTransId" varchar(20),
	"supplierTransId" varchar(20),
	"supplierId" varchar(20),
	"variantId" varchar(20),
	"action" varchar(20) NOT NULL,
	"targetPhone" varchar(11) NOT NULL,
	"serial" varchar(20) NOT NULL,
	"amount" numeric NOT NULL,
	"costAmount" numeric NOT NULL,
	"errorCode" varchar(10),
	"errorMessage" varchar(255)
);
